"""
Run this ONCE on your VPS to create your pre-filled .env file:
    python create_env.py
"""
import os

ENV_CONTENT = """# ════════════════════════════════════════════════════════
#  XCROW — Live Configuration  (generated by create_env.py)
# ════════════════════════════════════════════════════════

BOT_TOKEN=8850266161:AAG6T5HjR3LnGUR3Nb7xGECa2k1Ojcnoqks
BOT_USERNAME=XcrowVouchBot
ADMIN_IDS=7650247813
SUPPORT_USERNAME=XcrowBotsupport
WEBSITE_URL=

DATABASE_URL=postgresql+asyncpg://xcrow:xcrowpass@postgres:5432/xcrow

TRONGRID_API_KEY=2e2cd2eb-780c-4a71-b344-132f8524f7e3
BSCSCAN_API_KEY=MYRIT5YQPGJ6YKZGQTQJVJ23P1U4Z6QRB3
ETHERSCAN_API_KEY=MYRIT5YQPGJ6YKZGQTQJVJ23P1U4Z6QRB3

HD_MNEMONIC=screen vapor man plunge creek salad witness gasp sure rule path book same fee close example scatter obtain often quality used truck bag coast
WALLET_PASSPHRASE=

API_ID=38354178
API_HASH=3bd9e5fd70280a73a81149b33c1bc0d5
PHONE_NUMBER=+573142470443
SESSION_NAME=sessions/xcrow_user

API_HOST=0.0.0.0
API_PORT=8000
API_SECRET_KEY=xcrow-change-in-production

ESCROW_FEE_PERCENT=1.0
FEE_MODEL=buyer_pays

MONITOR_INTERVAL_SECONDS=30
CONFIRMATION_BLOCKS=1
LOG_LEVEL=INFO
"""

if os.path.exists(".env"):
    answer = input(".env already exists. Overwrite? (y/N): ").strip().lower()
    if answer != "y":
        print("Aborted.")
        raise SystemExit(0)

with open(".env", "w") as f:
    f.write(ENV_CONTENT.lstrip())

print("✅  .env created successfully.")
print("⚠️  Next step: run  python pyrogram_auth.py  to authenticate Pyrogram.")
